import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import html2canvas from 'html2canvas';
import { getTemporalData, getForecast, getViolationTypes, getVehicleTypes, getAIInsights } from '../api/backendApi';

// ── Letterhead / theme constants ─────────────────────────────────────
const COLORS = {
  navy: [21, 41, 79],
  navyLight: [37, 64, 110],
  gold: [180, 140, 40],
  textDark: [30, 30, 30],
  textMuted: [110, 110, 110],
  boxBg: [243, 246, 250],
  boxBorder: [200, 210, 225],
  red: [185, 38, 38],
  blue: [37, 99, 235],
  purple: [124, 58, 237],
  indigo: [67, 56, 202],
  emerald: [5, 150, 105],
  orange: [217, 100, 20],
};

const PAGE_MARGIN = 14;

/**
 * Draws the formal letterhead header. Call once per page where you
 * want the full letterhead (typically just page 1); subsequent pages
 * get the slimmer runningHeader instead.
 */
function drawLetterhead(doc, pageWidth, reportId) {
  // Top navy band
  doc.setFillColor(...COLORS.navy);
  doc.rect(0, 0, pageWidth, 28, 'F');

  // Gold accent rule under the band
  doc.setFillColor(...COLORS.gold);
  doc.rect(0, 28, pageWidth, 1.2, 'F');

  // Agency name / title
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.text('ParkIQ Traffic Enforcement Division', PAGE_MARGIN, 13);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10.5);
  doc.text('Bengaluru Traffic Police · Data-Driven Enforcement Report', PAGE_MARGIN, 20);

  // Report meta, right-aligned
  const today = new Date();
  const dateStr = today.toLocaleDateString('en-IN', { day: '2-digit', month: 'long', year: 'numeric' });
  doc.setFontSize(9);
  doc.text(`Report ID: ${reportId}`, pageWidth - PAGE_MARGIN, 12, { align: 'right' });
  doc.text(`Issued: ${dateStr}`, pageWidth - PAGE_MARGIN, 18, { align: 'right' });
  doc.text('Classification: Internal Use Only', pageWidth - PAGE_MARGIN, 24, { align: 'right' });

  doc.setTextColor(...COLORS.textDark);
}

/** Slim running header for pages after the first. */
function drawRunningHeader(doc, pageWidth, reportId) {
  doc.setFillColor(...COLORS.navy);
  doc.rect(0, 0, pageWidth, 12, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.text('ParkIQ Traffic Enforcement Report', PAGE_MARGIN, 8);
  doc.setFont('helvetica', 'normal');
  doc.text(reportId, pageWidth - PAGE_MARGIN, 8, { align: 'right' });
  doc.setTextColor(...COLORS.textDark);
}

/** Footer with page number + confidentiality line, drawn on every page. */
function drawFooter(doc, pageWidth, pageHeight, pageNum, totalPages) {
  doc.setDrawColor(...COLORS.boxBorder);
  doc.line(PAGE_MARGIN, pageHeight - 14, pageWidth - PAGE_MARGIN, pageHeight - 14);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(...COLORS.textMuted);
  doc.text(
    'Generated by ParkIQ Analytics · AI-assisted commentary, human review recommended before action.',
    PAGE_MARGIN,
    pageHeight - 9
  );
  doc.text(`Page ${pageNum} of ${totalPages}`, pageWidth - PAGE_MARGIN, pageHeight - 9, { align: 'right' });
  doc.setTextColor(...COLORS.textDark);
}

/**
 * Draws a shaded "insight" callout box with a left accent bar — used to
 * visually separate AI-generated commentary from raw tabular data.
 * Returns the Y position just below the box.
 */
function drawInsightBox(doc, { x, y, width, label, text, accentColor, pageHeight }) {
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9.5);

  const innerWidth = width - 14;
  const lines = doc.splitTextToSize(text, innerWidth);
  const lineHeight = 4.6;
  const labelHeight = 7;
  const boxHeight = labelHeight + lines.length * lineHeight + 6;

  // Page-break guard
  if (y + boxHeight > pageHeight - 18) {
    doc.addPage();
    y = 18;
  }

  // Box background + border
  doc.setFillColor(...COLORS.boxBg);
  doc.setDrawColor(...COLORS.boxBorder);
  doc.roundedRect(x, y, width, boxHeight, 2, 2, 'FD');

  // Left accent bar
  doc.setFillColor(...accentColor);
  doc.rect(x, y, 2.2, boxHeight, 'F');

  // Label
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(...accentColor);
  doc.text(label.toUpperCase(), x + 8, y + 6.5);

  // Body text
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9.5);
  doc.setTextColor(...COLORS.textDark);
  doc.text(lines, x + 8, y + 6.5 + labelHeight);

  return y + boxHeight + 10;
}

function sectionTitle(doc, text, x, y, color = COLORS.navy) {
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(15);
  doc.setTextColor(...color);
  doc.text(text, x, y);
  doc.setTextColor(...COLORS.textDark);
  return y + 8;
}

export const generateDashboardPDF = async ({ summary, hotspots, schedule, chartElements }) => {
  // ── Fetch extended analytics + AI insights in parallel ─────────────
  let forecast = [];
  let violations = [];
  let vehicles = [];
  let insights = null;

  try {
    const [fc, vi, ve] = await Promise.all([
      getForecast().catch(() => []),
      getViolationTypes().catch(() => []),
      getVehicleTypes().catch(() => []),
    ]);
    forecast = fc;
    violations = vi;
    vehicles = ve;
  } catch (err) {
    console.error('Failed to fetch extended analytics for PDF:', err);
  }

  try {
    insights = await getAIInsights({ summary, hotspots, schedule, forecast, violations, vehicles });
  } catch (err) {
    console.error('Failed to fetch AI insights for PDF:', err);
    insights = null;
  }

  // Safe fallback if insights fetch failed entirely
  const ai = insights || {
    executive_summary: 'AI-generated summary is currently unavailable.',
    metrics_insight: 'AI commentary unavailable for this section.',
    hotspot_insight: 'AI commentary unavailable for this section.',
    schedule_insight: 'AI commentary unavailable for this section.',
    forecast_insight: 'AI commentary unavailable for this section.',
    violation_insight: 'AI commentary unavailable for this section.',
    vehicle_insight: 'AI commentary unavailable for this section.',
  };

  const doc = new jsPDF('p', 'mm', 'a4');
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const contentWidth = pageWidth - PAGE_MARGIN * 2;
  const reportId = `PIQ-${new Date().toISOString().slice(0, 10).replace(/-/g, '')}-${Math.floor(Math.random() * 900 + 100)}`;

  let currentY = 38;

  // ── LETTERHEAD ───────────────────────────────────────────────────
  drawLetterhead(doc, pageWidth, reportId);

  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.navy);
  doc.text('Traffic Enforcement Analytics Report', PAGE_MARGIN, currentY);
  currentY += 10;

  // ── EXECUTIVE SUMMARY (AI) ──────────────────────────────────────────
  currentY = sectionTitle(doc, 'Executive Summary', PAGE_MARGIN, currentY);
  currentY = drawInsightBox(doc, {
    x: PAGE_MARGIN,
    y: currentY,
    width: contentWidth,
    label: 'AI Briefing',
    text: ai.executive_summary,
    accentColor: COLORS.navyLight,
    pageHeight,
  });

  // ── KEY METRICS ───────────────────────────────────────────────────
  if (summary) {
    if (currentY > 230) { doc.addPage(); currentY = 18; }
    currentY = sectionTitle(doc, 'Key Metrics', PAGE_MARGIN, currentY);

    const metrics = [
      ['Total Violations', summary.total_violations?.toLocaleString() || '-'],
      ['Hotspot Clusters', summary.total_clusters?.toLocaleString() || '-'],
      ['Critical Zones', summary.critical_zones?.toLocaleString() || '-'],
      ['Daily ROI (Top 10)', `Rs. ${summary.top10_roi?.toLocaleString() || '-'}`],
      ['Peak-Hour Share', `${summary.peak_pct || '-'}%`],
    ];

    autoTable(doc, {
      startY: currentY,
      head: [['Metric', 'Value']],
      body: metrics,
      theme: 'grid',
      headStyles: { fillColor: COLORS.navy },
      styles: { fontSize: 11 },
      margin: { left: PAGE_MARGIN, right: PAGE_MARGIN },
    });
    currentY = doc.lastAutoTable.finalY + 6;

    currentY = drawInsightBox(doc, {
      x: PAGE_MARGIN,
      y: currentY,
      width: contentWidth,
      label: 'What this means',
      text: ai.metrics_insight,
      accentColor: COLORS.navyLight,
      pageHeight,
    });
  }

  // ── TOP 10 CRITICAL ZONES ─────────────────────────────────────────
  if (hotspots && hotspots.length > 0) {
    if (currentY > 220) { doc.addPage(); currentY = 18; }
    currentY = sectionTitle(doc, 'Top 10 Critical Zones', PAGE_MARGIN, currentY, COLORS.red);

    const topZones = hotspots.slice(0, 10).map((h, i) => [
      i + 1,
      h.top_junction || 'Unknown',
      h.CCS_category || '-',
      `${h.CCS?.toFixed(1) || '-'} / 10`,
      h.violations || '-',
    ]);

    autoTable(doc, {
      startY: currentY,
      head: [['Rank', 'Location', 'Category', 'CCS Score', 'Violations']],
      body: topZones,
      theme: 'striped',
      headStyles: { fillColor: COLORS.red },
      styles: { fontSize: 10 },
      margin: { left: PAGE_MARGIN, right: PAGE_MARGIN },
    });
    currentY = doc.lastAutoTable.finalY + 6;

    currentY = drawInsightBox(doc, {
      x: PAGE_MARGIN,
      y: currentY,
      width: contentWidth,
      label: 'What this means',
      text: ai.hotspot_insight,
      accentColor: COLORS.red,
      pageHeight,
    });
  }

  // ── DEPLOYMENT SCHEDULE ───────────────────────────────────────────
  if (schedule && schedule.length > 0) {
    if (currentY > 220) { doc.addPage(); currentY = 18; }
    currentY = sectionTitle(doc, 'Deployment Schedule', PAGE_MARGIN, currentY, COLORS.blue);

    const scheduleData = schedule.map((s) => [
      s.top_junction || 'Unknown',
      s.deploy_window || '-',
      s.priority || '-',
    ]);

    autoTable(doc, {
      startY: currentY,
      head: [['Zone / Location', 'Time Window', 'Priority']],
      body: scheduleData,
      theme: 'striped',
      headStyles: { fillColor: COLORS.blue },
      styles: { fontSize: 10 },
      margin: { left: PAGE_MARGIN, right: PAGE_MARGIN },
    });
    currentY = doc.lastAutoTable.finalY + 6;

    currentY = drawInsightBox(doc, {
      x: PAGE_MARGIN,
      y: currentY,
      width: contentWidth,
      label: 'What this means',
      text: ai.schedule_insight,
      accentColor: COLORS.blue,
      pageHeight,
    });
  }

  // ── CHARTS (from Overview) ────────────────────────────────────────
  if (chartElements && chartElements.length > 0) {
    for (let i = 0; i < chartElements.length; i++) {
      const el = chartElements[i];
      if (!el) continue;

      if (currentY > 190) { doc.addPage(); currentY = 18; }

      try {
        const canvas = await html2canvas(el, { scale: 2, logging: false });
        const imgData = canvas.toDataURL('image/png');
        const imgWidth = contentWidth;
        const imgHeight = (canvas.height * imgWidth) / canvas.width;

        const title = i === 0 ? 'CCS Distribution' : i === 1 ? '#1 Hotspot Profile' : `Chart ${i + 1}`;
        currentY = sectionTitle(doc, title, PAGE_MARGIN, currentY);

        doc.setDrawColor(...COLORS.boxBorder);
        doc.rect(PAGE_MARGIN - 1, currentY - 1, imgWidth + 2, imgHeight + 2);
        doc.addImage(imgData, 'PNG', PAGE_MARGIN, currentY, imgWidth, imgHeight);
        currentY += imgHeight + 10;
      } catch (err) {
        console.error('Error capturing chart:', err);
      }
    }
  }

  // ── ANALYTICS & DATA APPENDIX ────────────────────────────────────
  doc.addPage();
  currentY = 18;

  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.navy);
  doc.text('Analytics & Comprehensive Data', PAGE_MARGIN, currentY);
  currentY += 12;
  doc.setTextColor(...COLORS.textDark);

  // Forecast
  if (forecast && forecast.length > 0) {
    currentY = sectionTitle(doc, 'Next 7-Day Risk Forecast', PAGE_MARGIN, currentY, COLORS.purple);

    const forecastData = forecast.map((f) => [
      f.date || '-', f.day || '-', f.risk || '-', f.peak_hours || '-', (f.top_zone || '').slice(0, 30),
    ]);

    autoTable(doc, {
      startY: currentY,
      head: [['Date', 'Day', 'Risk Level', 'Peak Hours', 'Top Risk Zone']],
      body: forecastData,
      theme: 'grid',
      headStyles: { fillColor: COLORS.purple },
      styles: { fontSize: 10 },
      margin: { left: PAGE_MARGIN, right: PAGE_MARGIN },
    });
    currentY = doc.lastAutoTable.finalY + 6;

    currentY = drawInsightBox(doc, {
      x: PAGE_MARGIN,
      y: currentY,
      width: contentWidth,
      label: 'What this means',
      text: ai.forecast_insight,
      accentColor: COLORS.purple,
      pageHeight,
    });
  }

  // Violation Types
  if (violations && violations.length > 0) {
    if (currentY > 210) { doc.addPage(); currentY = 18; }
    currentY = sectionTitle(doc, 'Top Violation Types Breakdown', PAGE_MARGIN, currentY, COLORS.indigo);

    const vData = violations.slice(0, 15).map((v) => [
      (v.vtype_list || '').slice(0, 60),
      v.count?.toLocaleString() || '-',
    ]);

    autoTable(doc, {
      startY: currentY,
      head: [['Violation Type', 'Total Count']],
      body: vData,
      theme: 'striped',
      headStyles: { fillColor: COLORS.indigo },
      styles: { fontSize: 10 },
      margin: { left: PAGE_MARGIN, right: PAGE_MARGIN },
    });
    currentY = doc.lastAutoTable.finalY + 6;

    currentY = drawInsightBox(doc, {
      x: PAGE_MARGIN,
      y: currentY,
      width: contentWidth,
      label: 'What this means',
      text: ai.violation_insight,
      accentColor: COLORS.indigo,
      pageHeight,
    });
  }

  // Vehicle Types
  if (vehicles && vehicles.length > 0) {
    if (currentY > 210) { doc.addPage(); currentY = 18; }
    currentY = sectionTitle(doc, 'Vehicle Type Distribution', PAGE_MARGIN, currentY, COLORS.emerald);

    const vehData = vehicles.map((v) => [v.vehicle || '-', v.count?.toLocaleString() || '-']);

    autoTable(doc, {
      startY: currentY,
      head: [['Vehicle Classification', 'Total Count']],
      body: vehData,
      theme: 'grid',
      headStyles: { fillColor: COLORS.emerald },
      styles: { fontSize: 10 },
      margin: { left: PAGE_MARGIN, right: PAGE_MARGIN },
    });
    currentY = doc.lastAutoTable.finalY + 6;

    currentY = drawInsightBox(doc, {
      x: PAGE_MARGIN,
      y: currentY,
      width: contentWidth,
      label: 'What this means',
      text: ai.vehicle_insight,
      accentColor: COLORS.emerald,
      pageHeight,
    });
  }

  // Extended Hotspots (Top 30)
  if (hotspots && hotspots.length > 10) {
    doc.addPage();
    currentY = 18;
    currentY = sectionTitle(doc, 'Extended Hotspots Directory (Top 30)', PAGE_MARGIN, currentY, COLORS.orange);

    const extendedZones = hotspots.slice(0, 30).map((h, i) => [
      i + 1,
      (h.top_junction || 'Unknown').slice(0, 40),
      h.CCS_category || '-',
      `${h.CCS?.toFixed(1) || '-'}`,
      h.violations?.toLocaleString() || '-',
      `${h.peak_pct || '-'}%`,
    ]);

    autoTable(doc, {
      startY: currentY,
      head: [['Rank', 'Location / Junction', 'Category', 'CCS', 'Violations', 'Peak %']],
      body: extendedZones,
      theme: 'striped',
      headStyles: { fillColor: COLORS.orange },
      styles: { fontSize: 9 },
      margin: { left: PAGE_MARGIN, right: PAGE_MARGIN },
    });
  }

  // ── RUNNING HEADERS + FOOTERS ON ALL PAGES ──────────────────────────
  const totalPages = doc.internal.getNumberOfPages();
  for (let p = 1; p <= totalPages; p++) {
    doc.setPage(p);
    if (p > 1) drawRunningHeader(doc, pageWidth, reportId);
    drawFooter(doc, pageWidth, pageHeight, p, totalPages);
  }

  doc.save(`ParkIQ_Comprehensive_Report_${new Date().toISOString().split('T')[0]}.pdf`);
};